#!/bin/bash
# By Sam Gleske (sag47)
# Created 2012/04/10
# Linux 2.6.18-194.11.4.el5 x86_64 GNU/Linux
# GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
#
# live_trend info
# This live_trend program samples every second.
# This program will not output if the current second sample is the same as the last second sample.
# That way only unique entries with associated timestamps will be output.
# All proceeding timestamp entries not output are assumed to be the same value as the current timestamp value.
#
# open_file_descriptors_live_trend info
# This trending program shows the number of open file descriptors over time.  This is useful because users are limited to 1024 (see ulimit -n).
# You configure some of the variables for the specific user you wish to analyze. See # CONFIGURE VARIABLES section
# Output format
#     Number of open file descriptors = ####; local date and time in human readable format; date in seconds since 1970-01-01 00:00:00 UTC

# CONFIGURE VARIABLES
user="jboss"

# END CONFIGURE VARIABLES
while true;do 
  current="$user user open file descriptors = $(lsof | awk 'BEGIN{count=0}; ($3 == "jboss") {count++}; END{print count}')"
  date=$(date '+%Y-%m-%d %I:%M:%S %p')
  dates=$(date '+%s')
  if [ "$current" != "$last" ];then
    echo "$current; $date; $dates";
  fi
  last=$current
  sleep 1
done
