#!/bin/sh
#Created by Sam Gleske (sag47@drexel.edu)

# chkconfig: 2345 80 80
# description: starts JBoss

### BEGIN INIT INFO
# Provides: jboss
# Required-Start: $network
# Defalt-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: starts JBoss
### END INIT INFO

# source function library
if [ -f /etc/rc.d/init.d/functions ]; then
. /etc/rc.d/init.d/functions
fi

if [ -f /lib/lsb/init-functions ]; then
. /lib/lsb/init-functions
fi

#define where jboss is - this is the directory containing directories log, bin, conf etc
JBOSS_HOME=${JBOSS_HOME:-"/app/jboss"}

#define the user under which jboss will run, or use 'RUNASIS' to run as the current user
JBOSS_USER=${JBOSS_USER:-"jboss"}

#make sure java is in your path
JAVAPTH=${JAVAPTH:-"/app/java/bin"}

#Command to start jboss; recommended to change the default binding and profile
JBOSS_CMD_START="$JBOSS_HOME/bin/run.sh -b 0.0.0.0"

#define what will be done with the console log
JBOSS_CONSOLE=${JBOSS_CONSOLE:-"/dev/null"}

if [ "$JBOSS_USER" = "RUNASIS" ]; then
  SUBIT=""
else
  SUBIT="su - $JBOSS_USER -c "
fi

if [ -n "$JBOSS_CONSOLE" -a ! -d "$JBOSS_CONSOLE" ]; then
  if [ ! "$JBOSS_CONSOLE" = "/dev/null" ];then
    # ensure the file exists
    touch $JBOSS_CONSOLE
    if [ ! -z "$SUBIT" ]; then
      chown $JBOSS_USER $JBOSS_CONSOLE
    fi 
  fi
fi

#if [ -n "$JBOSS_CONSOLE" -a ! -f "$JBOSS_CONSOLE" ]; then
#  echo "WARNING: location for saving console log invalid: $JBOSS_CONSOLE"
#  echo "WARNING: ignoring it and using /dev/null"
#  JBOSS_CONSOLE="/dev/null"
#fi

if [ -z "`echo $PATH | grep $JAVAPTH`" ]; then
  export PATH=$PATH:$JAVAPTH
fi

if [ ! -d "$JBOSS_HOME" ]; then
  echo "JBOSS_HOME does not exist as a valid directory : $JBOSS_HOME"
  exit 1
fi

#custom functions added by Sam
start() {
  cd $JBOSS_HOME/bin
  echo JBOSS_CMD_START = $JBOSS_CMD_START
  if [ -z "$SUBIT" ]; then
    eval $JBOSS_CMD_START >${JBOSS_CONSOLE} 2>&1 &
  else
    $SUBIT "$JBOSS_CMD_START >${JBOSS_CONSOLE} 2>&1 &" 
  fi
}

wait() {
  while true;do
    pid=`ps aux | awk '($1 == "'$JBOSS_USER'") && ($0 ~ /java/) {print $2}'`
    if [ -z "$pid" ];then
      return 0
    else
      sleep 1
      echo -n "."
    fi
  done
}

stop() {
  #Sam's custom kill command for jboss
  kill -s 15 `ps aux | awk '($1 == "'$JBOSS_USER'") && ($0 ~ /java/) {print $2}'` 2> /dev/null
  if [ "$?" -eq "0" ];then
    echo -n "JBoss is stopping."
    wait && success
    echo ""
  else
    failure
    echo "JBoss not running..."
  fi

}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status java
    ;;
  *)
    echo "usage: $0 (start|stop|restart|status|help)"
esac

