#!/bin/sh
#Created by Sam Gleske (sag47@drexel.edu)

# chkconfig: 2345 80 80
# description: starts tomcat

### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $network
# Defalt-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: starts tomcat
### END INIT INFO

# source function library
if [ -f /etc/rc.d/init.d/functions ]; then
. /etc/rc.d/init.d/functions
fi

if [ -f /lib/lsb/init-functions ]; then
. /lib/lsb/init-functions
fi

#define where jboss is - this is the directory containing directories log, bin, conf etc
TOMCAT_HOME=${TOMCAT_HOME:-"/app/tomcat"}

#define the user under which jboss will run, or use 'RUNASIS' to run as the current user
TOMCAT_USER=${TOMCAT_USER:-"tomcat"}

#make sure java is in your path
JAVAPTH=${JAVAPTH:-"/app/java/bin"}

#Command to start tomcat
TOMCAT_CMD_START="$TOMCAT_HOME/bin/startup.sh"

if [ "$TOMCAT_USER" = "RUNASIS" ]; then
  SUBIT=""
else
  SUBIT="su - $TOMCAT_USER -c "
fi

if [ -n "$TOMCAT_CONSOLE" -a ! -d "$TOMCAT_CONSOLE" ]; then
  # ensure the file exists
  touch $TOMCAT_CONSOLE
  if [ ! -z "$SUBIT" ]; then
    chown $TOMCAT_USER $TOMCAT_CONSOLE
  fi 
fi

if [ -n "$TOMCAT_CONSOLE" -a ! -f "$TOMCAT_CONSOLE" ]; then
  echo "WARNING: location for saving console log invalid: $TOMCAT_CONSOLE"
  echo "WARNING: ignoring it and using /dev/null"
  TOMCAT_CONSOLE="/dev/null"
fi

#define what will be done with the console log
TOMCAT_CONSOLE=${TOMCAT_CONSOLE:-"/dev/null"}

if [ -z "`echo $PATH | grep $JAVAPTH`" ]; then
  export PATH=$PATH:$JAVAPTH
fi

if [ ! -d "$TOMCAT_HOME" ]; then
  echo TOMCAT_HOME does not exist as a valid directory : $TOMCAT_HOME
  exit 1
fi

#custom functions added by Sam
start() {
    cd $TOMCAT_HOME/bin
    echo TOMCAT_CMD_START = $TOMCAT_CMD_START
    
    if [ -z "$SUBIT" ]; then
        eval $TOMCAT_CMD_START >${TOMCAT_CONSOLE} 2>&1 &
    else
        $SUBIT "$TOMCAT_CMD_START >${TOMCAT_CONSOLE} 2>&1 &" 
    fi
}

wait() {
    while true;do
      pid=`ps aux | grep "^$TOMCAT_USER" | grep java | awk '{print $2}'`
      if [ -z $pid ];then
	return 0
      else
	sleep 1
	echo -n "."
      fi
    done
}

stop() {
    #Sam's custom kill command for jboss
    kill -s 15 `ps aux | grep "^$TOMCAT_USER" | grep java | awk '{print $2}'` 2> /dev/null
    if [ "$?" -eq "0" ];then
        echo -n "Tomcat is stopping."
	wait && success
	echo ""
    else
        failure
        echo "Tomcat not running..."
    fi

}

restart() {
    stop
    start
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
status)
    status java
    ;;
*)
    echo "usage: $0 (start|stop|restart|status|help)"
esac

